(() => {
'use strict';
const screen=document.getElementById('screen'),overlay=document.getElementById('overlay');
const labels={shop:'消費購物',play:'遊戲玩樂',life:'生活娛樂'};
const art=(name,alt='')=>`<img class="visual-art" src="assets/visual/${name}.png" alt="${alt}">`;
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${{shop:'<path d="M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2"/>',play:'<path d="M6 7h12c2 0 3 2 3 4l1 6c0 2-2 3-4 1l-3-2H9l-3 2c-2 2-4 1-4-1l1-6c0-2 1-4 3-4Z"/><path d="M6 11h4m-2-2v4m8-2h.01m2 2h.01"/>',life:'<path d="M4 4h14v9a7 7 0 0 1-14 0V4Zm14 2h2a3 3 0 0 1 0 6h-2M3 22h18"/>',invoice:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M8 6v8m3-8v8m3-8v8m2-8v8M8 18h8"/>',health:'<path d="M12 19 4 11a5 5 0 0 1 8-6 5 5 0 0 1 8 6l-8 8ZM3 17v3l3 2h12l3-2v-3"/>',settings:'<path d="m9 3 1-2h4l1 2 3 1 2 3-1 2v6l1 2-2 3-3 1-1 2h-4l-1-2-3-1-2-3 1-2V9L4 7l2-3 3-1Z"/><circle cx="12" cy="12" r="4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',gift:'<rect x="3" y="8" width="18" height="4" rx="1"/><path d="M5 12v9h14v-9M12 8v13M12 8H7a3 3 0 1 1 3-3l2 3Zm0 0h5a3 3 0 1 0-3-3l-2 3Z"/>',task:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="m8 10 2 2 4-4M8 16h8M9 4V2h6v2"/>',ticket:'<path d="M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4V5ZM15 5v14"/>',send:'<path d="m3 10 18-7-7 18-3-8-8-3Zm8 3L21 3"/>'}[name]||''}</svg>`;
const robot='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 8V4m-2 0h4"/><rect x="4" y="8" width="16" height="12" rx="4"/><path d="M4 13H2m18 0h2M9 16h6"/><circle cx="9" cy="12" r=".8"/><circle cx="15" cy="12" r=".8"/></svg>';
let state,history=[],current={},timers=[],rotation;
let fabCollapseTimer,fabReminderTimer,fabReturnTimer,fabReminders=0;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=()=>'<div class="status"><span>9:18</span><span class="signals">▮▮▮ ◔ ▰</span></div>';
const topbar=(title,side='')=>`${status()}<header class="topbar"><button class="back" data-action="back" aria-label="返回">‹</button><h1>${title}</h1>${side||'<span class="side"></span>'}</header>`;
const button=(label,action,classes='btn',extra='')=>`<button class="${classes}" data-action="${action}" ${extra}>${label}</button>`;
const imagePage=(asset,controls='')=>`<div class="image-screen"><img src="assets/${asset}.png" alt="${asset==='home'?'HAPPY GO 首頁':asset==='selection'?'GO驚喜三大類型選擇':asset==='lancome'?'蘭蔻簽到活動':'票券商品詳情'}">${controls}</div>`;
const cropImage=(asset,x,y,w,h,sw=869,sh=1884)=>`<svg viewBox="${x} ${y} ${w} ${h}" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><defs><clipPath id="crop-${asset}-${x}-${y}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs><image href="assets/${asset}.png" width="${sw}" height="${sh}" clip-path="url(#crop-${asset}-${x}-${y})"/></svg>`;
const hotspot=(label,action,x,y,w,h,extra='')=>`<button class="hotspot" aria-label="${label}" data-action="${action}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" ${extra}>${label}</button>`;
function schedule(fn,delay){const id=setTimeout(fn,delay);timers.push(id);return id;}
function pauseFab(){clearTimeout(fabCollapseTimer);clearTimeout(fabReminderTimer);clearTimeout(fabReturnTimer);screen.querySelector('.ai-fab')?.classList.remove('peeking');}
function fabAvailable(){return current.page==='category'&&!document.hidden&&!overlay.innerHTML;}
function queueFabReminder(){clearTimeout(fabReminderTimer);const fab=screen.querySelector('.ai-fab');if(!fabAvailable()||!fab?.classList.contains('collapsed')||fabReminders>=3||reducedMotion.matches)return;fabReminderTimer=setTimeout(()=>{if(!fabAvailable()||!fab.isConnected||reducedMotion.matches)return;if(fab.matches(':focus-visible')){queueFabReminder();return;}fabReminders++;fab.dataset.reminders=fabReminders;fab.classList.add('peeking');fabReturnTimer=setTimeout(()=>{fab.classList.remove('peeking');queueFabReminder();},1200);},10000);}
function resumeFab(){if(!fabAvailable())return;const fab=screen.querySelector('.ai-fab');if(!fab)return;if(fab.classList.contains('collapsed'))queueFabReminder();else{clearTimeout(fabCollapseTimer);fabCollapseTimer=setTimeout(()=>{if(!fabAvailable())return;fab.classList.add('collapsed');queueFabReminder();},4000);}}
function startFab(){fabReminders=0;const fab=screen.querySelector('.ai-fab');if(fab)fab.dataset.reminders='0';resumeFab();}
function noteFabActivity(){if(current.page!=='category')return;pauseFab();resumeFab();}
function clearPending(){pauseFab();if(state?.pending){state.chat.push({role:'assistant',text:'剛才的整理已中斷，你可以重新提問。'});state.pending=0;}timers.forEach(clearTimeout);timers=[];if(rotation)clearInterval(rotation);}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('visible');schedule(()=>el.classList.remove('visible'),2200);}
function reset(clearFortune=false){if(clearFortune){Object.keys(localStorage).filter(key=>/^lucky-demo-\d{4}-\d{2}-\d{2}$/.test(key)).forEach(key=>localStorage.removeItem(key));}clearPending();state={category:'shop',balance:800,campaign:0,consumptionCount:2,claimed:false,redeemed:false,coupon:false,linked:false,qty:1,chat:[],preferences:false,fromEgg:false};history=[];navigate('home',{},false);}
function navigate(page,args={},remember=true){clearPending();if(remember&&current.page)history.push({...current});current={page,...args};overlay.innerHTML='';screen.innerHTML=render();screen.scrollTop=0;document.getElementById('toast').classList.remove('visible');if(page==='category'){startCarousel();startFab();}if(page==='ai')scrollChat();}
function back(){if(overlay.innerHTML){overlay.innerHTML='';resumeFab();return;}const previous=history.pop();if(previous)navigate(previous.page,previous,false);else navigate('home',{},false);}
function enterCategory(type){state.category=type;navigate('category');}
function modal(html,variant=''){pauseFab();overlay.innerHTML=`<div class="modal-shade"><section class="modal ${variant}" role="dialog" aria-modal="true">${variant==='sign-complete'?'':button('×','close','close','aria-label="關閉"')}${html}</section></div>`;schedule(()=>overlay.querySelector('button')?.focus(),20);}
function render(){switch(current.page){
case 'home':return imagePage('home','<div class="home-services-label" role="heading" aria-level="2">熱門服務</div>'+ hotspot('進入 GO驚喜 個人專屬','selection',74,70,25,15)+`<div style="position:absolute;left:39.5%;top:22.1%;width:21%;height:3.8%;font-size:36px;color:white;background:linear-gradient(100deg,#b8a7dd,#b4a6df);padding-left:2px">${state.balance.toLocaleString()}</div>`);
case 'selection':return imagePage('selection',hotspot('返回首頁','back',2,6,10,5)+hotspot('選擇消費購物','choose-shop',3,25,94,21)+hotspot('選擇遊戲玩樂','choose-play',3,47,94,22)+hotspot('選擇生活娛樂','choose-life',3,69,94,22)+hotspot('先逛消費購物','choose-shop',4,91.5,92,7));
case 'category':return renderCategory();
case 'task-list':return `<article class="native-page">${topbar('彩蛋任務')}<div class="page-content"><div class="note">${state.claimed?'今日的額外 10 點已收下。':'完成以下指定任務，可額外獲得 10 點。'}</div><section class="task-list-card"><div class="task-list-art" role="img" aria-label="蘭蔻長壽膠囊精華活動">${cropImage('tasks',44,318,780,401)}</div><h2>蘭蔻全新【長壽膠囊精華】，簽到享試用！</h2><p>活動至 2026/10/11</p>${button('前往簽到','task-detail','btn full')}</section></div></article>`;
case 'task-detail':return imagePage('lancome',hotspot('返回彩蛋任務列表','back',2,5,10,5)+hotspot('立即簽到','sign',8,89,84,6));
case 'ticket-detail':return imagePage('sogo',hotspot('返回','back',2,7,10,5)+hotspot('立即兌換','quantity',52,91.5,44,6)+hotspot('送禮物','gift-info',4,91.5,44,6));
case 'coco-detail':return renderCoco();
case 'quantity':return renderQuantity();
case 'wallet':return renderWallet();
case 'invoice':return `<article class="native-page">${topbar('電子發票')}<div class="page-content"><section class="invoice-panel"><div class="big">▤</div><h2>手機條碼載具</h2><div class="linked">${state.linked?'已重新綁定':'已綁定'}</div><p>重新確認載具綁定，即可解鎖本次彩蛋專屬優惠。</p>${button(state.linked?'查看專屬優惠':'重新綁定載具','link-carrier','btn full')}</section></div></article>`;
case 'invoice-forest':return `<article class="native-page">${topbar('發票森林')}<div class="page-content"><section class="forest-panel"><h2>你的發票戰士</h2>${art('invoice-warrior','女性發票戰士')}<p>和你的發票戰士一起，探索發票森林。</p>${button('查看電子發票','invoice','btn full')}</section>${button('回 GO驚喜','return-category','btn light full')}</div></article>`;
case 'ai':return renderAI();
case 'fortune':return `<article class="fortune-page"><iframe class="fortune-frame" title="求個好運：今日幸運夥伴" src="fortune/?embedded=1" allow="clipboard-write; web-share"></iframe></article>`;
case 'service':return `<article class="native-page">${topbar(current.title)}<div class="page-content"><div class="note">${current.description}</div>${current.visualAsset?`<div class="service-promo-art">${art(current.visualAsset,'點數補給計畫，完成任務贈30點')}</div>`:''}${current.toolIcon?`<div class="service-tool-art">${art('tool-'+current.toolIcon)}</div>`:''}${current.asset?`<div class="banner-clip" style="height:350px;background-image:url('assets/${current.asset}.png');background-size:100% auto;background-position:center ${current.position||'24%'}"></div>`:''}${button('回 GO驚喜','return-category','btn full')}</div></article>`;
default:return '';}}
function renderCategory(){const type=state.category;return `<article class="category" data-type="${type}">${topbar('<em>GO</em>驚喜｜個人專屬')}<div class="greeting">${art('avatar')}<div><strong>Hi，吳*花</strong><p>${{shop:'為你精選省點、賺點的好康',play:'今天，也來點好玩的吧',life:'生活裡的好康，為你準備好了'}[type]}</p></div><span class="diamond">◆ 鑽點</span></div><nav class="tabs" aria-label="內容類型" role="tablist">${Object.entries(labels).map(([k,v])=>button(icon(k)+v,'tab',' '+(k===type?'active':''),`role="tab" aria-selected="${k===type}" data-type="${k}"`)).join('')}</nav><div class="modules">${type==='life'?lifeModules():standardModules(type)}<button class="egg" data-action="eggs"><div class="egg-art" aria-hidden="true">${art('egg-gift-transparent')}</div><div><strong>今日彩蛋</strong><span>${state.claimed?'你的驚喜已收下，還有更多好康':'打開看看，今天有什麼驚喜？'}</span></div><span class="arrow" aria-hidden="true">›</span></button>${tools()}<div class="bottom-spacer"></div></div><span class="ai-fab-label">AI 點數管家</span><button class="ai-fab" aria-label="鑽點會員專屬 AI 點數管家" data-action="ai">${art('robot')}</button></article>`;}
function standardModules(type){if(type=='play')return playModules();const top=type==='shop'?`<section class="primary-card"><h2 class="section-label">消費加碼活動 <small>今日精選</small></h2><div class="campaign-body"><div class="campaign-art" role="img" aria-label="消費滿7筆贈100點">${art('campaign-redpacket','鑽點專屬：消費累點滿7筆，贈100點')}</div><div class="campaign-info"><h3>【鑽點購物紅包】<br>消費滿7筆贈100點</h3><div class="progress" aria-label="目前消費進度 ${state.consumptionCount} 筆，目標 7 筆"><span style="width:${Math.min(state.consumptionCount/7*100,100)}%"></span></div><div class="progress-value"><strong>${state.consumptionCount}</strong> ／ 7 筆</div></div></div><div class="campaign-footer"><span class="deadline">截止：2026/10/31</span>${button('查看進度','campaign-progress')}${button('活動說明','campaign-info','btn orange')}</div></section>`:`<section class="primary-card"><h2 class="section-label">指定任務 <small>今日精選</small></h2><button class="daily-task" data-action="birthday-info" aria-label="領取您的發票壽星禮 大杯拿鐵限量搶">${art('birthday')}</button><div class="task-footer"><span>領取您的發票壽星禮！</span>${button('查看任務','birthday-info','btn orange')}</div></section>`;
return top+`<div class="two-col">${type==='shop'?tile('優惠活動','offers','offer', '精選合作品牌優惠')+tile('購賺點','shopping','shopping','生活每一筆，都值得被回饋'):tile('遊戲樂園','game','games','玩遊戲，完成任務賺點')+tile('GO HEALTH','health','health','動腦遊戲，讓健康有人陪')}</div>`;}
const playCopy={game:[['玩遊戲，點數兩倍贈','完成任務，賺點更有感'],['限時遊戲任務','探索挑戰，完成任務'],['探索新遊戲','找到你的下一個樂趣']],health:[['首玩加碼','動腦挑戰，健康有伴'],['健康小學堂','動腦挑戰，健康有伴'],['每天動腦','開啟你的健康時光']]};
function playBanner(key,index){return art(bannerNames(key)[index],playCopy[key][index].join('，'));}
function playTile(title,key,action){return `<section class="tile" data-banner="${key}" data-slide="0"><h2>${title}</h2><button class="banner-link" data-action="${action}" aria-label="${title}：${playCopy[key][0].join('，')}">${playBanner(key,0)}</button><div class="play-card-footer"><div class="dots" aria-label="${title}輪播">${[0,1,2].map(i=>button('','banner-slide','dot'+(i===0?' current':''),`data-index="${i}" aria-label="第 ${i+1} 張" aria-pressed="${i===0}"`)).join('')}</div></div></section>`;}
function playModules(){return `<div class="play-service-grid"><section class="warrior-card"><h2>你的發票戰士</h2><div class="warrior-stage">${art('invoice-forest-background','森林場景')}${art('invoice-warrior','橘色辮髮、綠葉服裝的女性發票戰士')}</div>${button('前往查看<br>發票森林','invoice-forest','btn forest-entry')}</section><div class="play-service-stack"><section class="tile play-task-card"><h2>指定任務 <small>今日精選</small></h2><button class="banner-link daily-task" data-action="daily-task-info" aria-label="點數補給計畫，完成任務贈30點">${art('task-points-supply-wide','點數補給計畫，完成任務贈30點')}</button><div class="play-card-footer"><span>查看今日任務 ›</span></div></section>${playTile('遊戲樂園','game','games')}${playTile('GO HEALTH','health','health')}</div></div>`;}
function tile(title,key,action,caption){return `<section class="tile" data-banner="${key}" data-slide="0"><h2>${title}</h2><button class="banner-link" data-action="${action}" aria-label="${title}">${art(bannerNames(key)[0])}</button><div class="dots" aria-label="${title}輪播">${[0,1,2].map(i=>button('','banner-slide','dot'+(i===0?' current':''),`data-index="${i}" aria-label="第 ${i+1} 張" aria-pressed="${i===0}"`)).join('')}</div></section>`;}
function lifeModules(){return `<div class="life-grid"><section class="ticket-combined" aria-label="兌點加碼活動與推薦票券"><section class="ticket-pane"><h2>兌點加碼活動</h2><button class="ticket-banner" data-action="ticket-event" aria-label="累積兌點滿240點，贈10點">${art('ticket-event-fullbleed','累積兌點滿240點，贈10點')}</button><div class="ticket-description">累積兌點滿240點，贈10點</div><div class="ticket-footer">${button('活動說明','ticket-event','small-cta')}</div></section><section class="ticket-pane"><h2>推薦票券 <small>${state.balance}點內</small></h2><button class="ticket-banner" data-action="coco-detail" aria-label="CoCo 都可珍珠鮮奶">${art('coco-fullbleed','CoCo 都可珍珠鮮奶')}</button><div class="ticket-description">CoCo 都可珍珠鮮奶</div><div class="ticket-footer"><span class="points">Ⓟ 260</span>${button('兌換','coco-detail','small-cta')}</div></section></section>${tile('優惠活動','offers','offer','生活優惠，為你精選')}${tile('旅遊交通','utag','utag','交通、外出點數應用')}</div>`;}
const toolDefaults={shop:[{label:'點數安全鎖',asset:'security',description:'管理 HAPPY GO 點數使用的安全設定。'},{label:'附近店家',asset:'nearby',description:'查看附近可使用 HAPPY GO 的合作店家。'},{label:'免運到貨',asset:'shipping',description:'查看購物與免運到貨服務。'},{label:'領神券',asset:'coupon',description:'查看可領取的優惠券與合作品牌活動。'}],play:[{label:'會員權益',asset:'membership',description:'查看會員等級與專屬權益。'},{label:'問卷得點',asset:'survey',description:'查看問卷活動與得點機會。'},{label:'星座運勢',asset:'horoscope',description:'查看星座運勢與生活小提醒。'},{label:'求個好運',asset:'fortune',action:'fortune',description:'抽支好運籤，為今天添一點好心情。'}],life:[{label:'熱門兌換',asset:'redeem',description:'探索熱門票券與點數兌換商品。'},{label:'點數放大',asset:'amplify',description:'查看點數加碼與使用方式。'},{label:'永續生活',asset:'sustainable',description:'探索永續生活與環保相關服務。'},{label:'便利服務',asset:'convenience',description:'查看生活便利與合作服務。'}]};
function tools(){return `<section class="tools"><div class="tools-title">自訂小工具 ${button('編輯','edit-tools','')}</div><div class="tool-grid">${toolDefaults[state.category].map((t,i)=>{const content=`<span class="tool-circle">${art('tool-'+t.asset)}</span><span class="tool-label">${t.label}</span>`;return t.href?`<a class="tool-link" href="${t.href}" target="_blank" rel="noopener" aria-label="${t.label}，在新分頁開啟">${content}</a>`:`<button data-action="${t.action||'tool-service'}" data-tool-index="${i}">${content}</button>`;}).join('')}</div></section>`;}
function bannerNames(key){return {offers:state.category==='life'?['life-offer-biccamera','life-offer-books','life-offer-saily']:['shop-offer-anniversary','shop-offer-tea','shop-offer-dome'],shopping:['shop-coupang-20261005','shop-shopee-mall-20261005','shop-shopee-market-20261005'],game:['play-game-1-promo','play-game-2-promo','play-game-3-promo'],health:['play-health-1-promo','play-health-2-promo','play-health-3-promo'],utag:['travel-etag-20261005','travel-parking-20261005','travel-dodohome-20261005']}[key];}
function setBanner(tile,index){tile.dataset.slide=index;tile.querySelectorAll('.dot').forEach((dot,i)=>{dot.classList.toggle('current',i===index);dot.setAttribute('aria-pressed',String(i===index));});const link=tile.querySelector('.banner-link'),key=tile.dataset.banner;if(playCopy[key]){link.innerHTML=playBanner(key,index);link.setAttribute('aria-label',(key==='game'?'遊戲樂園':'GO HEALTH')+'：'+playCopy[key][index].join('，'));}else link.innerHTML=art(bannerNames(key)[index]);}
function startCarousel(){rotation=setInterval(()=>{if(!document.hidden&&!overlay.innerHTML)screen.querySelectorAll('[data-banner]').forEach(el=>setBanner(el,(Number(el.dataset.slide)+1)%3));},4500);}
function showEggs(){modal(`<div class="egg-heading">${art('egg-gift-transparent')}</div><h2>今日彩蛋</h2><p>完成指定行動，解鎖今天的專屬好康</p><button class="egg-choice" data-action="egg-ticket"><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 5h16v5a2 2 0 0 0 0 4v5H4v-5a2 2 0 0 0 0-4V5Z"/><path d="M15 5v2m0 3v2m0 3v4"/></svg></span><div><strong>兌換指定票券</strong><small>贈 10% 點數回饋券</small></div></button><button class="egg-choice orange" data-action="egg-task"><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="m8 10 2 2 4-4m-6 8h8"/></svg></span><div><strong>完成指定任務</strong><small>${state.claimed?'今日加碼 10 點已領取':'加碼贈 10 點 HAPPY GO 點數'}</small></div></button><button class="egg-choice" data-action="egg-carrier"><span>▤</span><div><strong>重新綁定載具</strong><small>解鎖專屬優惠</small></div></button>`);}
function sign(){modal(`<h2>簽到完成！</h2><p>符合指定簽到次數就能得點數，<br>別忘了要回來簽到喔！</p><div class="dialog-actions">${button('確定','signed-confirm')}${button('看更多','signed-more','btn orange')}</div>`,'sign-complete');}
function surprise(kind){const ticket=kind==='ticket';overlay.innerHTML=`<div class="modal-shade"><section class="modal reward-modal" role="dialog" aria-modal="true">${ticket?'<img class="reward-art" src="assets/drop.png" alt="Happy Drop 驚喜降臨">':'<div class="reward-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="8" width="18" height="4" rx="1"/><path d="M5 12v8h14v-8M12 8v12M12 8H7.5A2.5 2.5 0 1 1 10 5.5L12 8Zm0 0h4.5A2.5 2.5 0 1 0 14 5.5L12 8Z"/></svg></div><h2>驚喜降臨！</h2><div class="reward-caption">恭喜完成指定任務</div><div class="reward-number">10 <small>點</small></div><div class="reward-caption">額外獲得 HAPPY GO 點數</div>'}${ticket?'<h2>獲得 10% 點數回饋券</h2><p>下次兌換指定商品，可享點數 10% 回饋；兌換 100 點商品，可再獲得 10 點。</p>':''}${button(ticket?'查看我的票券':'收下驚喜',ticket?'claim-coupon':'claim-points','btn orange full')}${ticket?'':button('回 GO驚喜','claim-return','btn light full')}</section></div>`;for(let i=0;i<35;i++){const confetti=document.createElement('i');confetti.className='confetti';confetti.style.left=`${Math.random()*100}%`;confetti.style.background=['#fbb238','#9f78df','#fba5b7','#83c7b3'][i%4];confetti.style.animationDelay=`${Math.random()*.9}s`;overlay.querySelector('.modal-shade').appendChild(confetti);}}
function renderCoco(){return `<article class="native-page">${topbar('票券詳情')}<div class="page-content"><div class="crop-coco" style="height:420px;border-radius:25px;background-size:200% auto"></div><h2>CoCo 都可珍珠鮮奶</h2><p class="balance-pill">Ⓟ 260 點</p><p>以 HAPPY GO 點數兌換你喜歡的茶飲。</p>${button('立即兌換','quantity-coco','btn full')}</div></article>`;}
function renderQuantity(){const coco=current.product==='coco';const cost=coco?260:200;return `<article class="native-page">${topbar('請選擇兌換份數',`<span class="balance-pill">Ⓟ ${state.balance}</span>`)}<div class="page-content"><section class="wallet-card"><div class="${coco?'crop-coco':'crop-sogo'}" style="width:100px;height:105px;border-radius:15px;flex:none"></div><div><h2>${coco?'CoCo 都可珍珠鮮奶':'大巨蛋店 100 元電子購物金'}</h2><p>每份 ${cost} 點</p></div></section><h2>請選擇兌換份數</h2><div style="display:flex;align-items:center;justify-content:space-between;padding:20px;background:white;border-radius:20px">${button('−','minus','btn')}<strong style="font-size:39px" id="qty">${state.qty}</strong>${button('＋','plus','btn')}</div><p style="display:flex;justify-content:space-between">兌換點數總計 <strong style="color:#f48d18" id="total">Ⓟ ${cost*state.qty}</strong></p><h2>請確認資料</h2><section class="invoice-panel" style="text-align:left"><p>姓名 <span style="float:right">吳*花</span></p><p>手機號碼 <span style="float:right">09********</span></p><p>電子郵件 <span style="float:right">已驗證</span></p></section><p style="font-size:21px">✓ 本人已詳閱告知事項並同意使用會員資料進行票券兌換。</p>${button('立即兌換','redeem-confirm','btn full')}</div></article>`;}
function redeemConfirm(){const cost=current.product==='coco'?260:200;modal(`<h2>HAPPY GO 商品兌換</h2><p>商品一經兌換無法更改或取消。<br>確定使用 ${cost*state.qty} 點兌換 ${state.qty} 份嗎？</p><div class="dialog-actions">${button('取消','close','btn light')}${button('確定','redeem','btn orange')}</div>`);}
function redeem(){const cost=current.product==='coco'?260:200;if(state.balance<cost*state.qty){modal(`<h2>點數不足</h2><p>目前有 ${state.balance} 點。可以請 AI 點數管家推薦其他選擇。</p>${button('請 AI 幫我推薦','ai','btn full')}`);return;}state.balance-=cost*state.qty;state.campaign+=cost*state.qty;state.redeemed=true;modal(`<h2>成功兌換</h2><p>使用 ${cost*state.qty} 點成功兌換 ${state.qty} 張${current.product==='coco'?'CoCo 都可珍珠鮮奶':'大巨蛋店 100 元電子購物金'}票券。</p><div class="dialog-actions">${button('繼續兌換','redemption-next','btn light')}${button('管理票券','redemption-next','btn orange')}</div>`);}
function renderWallet(){return `<article class="native-page">${topbar('我的票券')}<div class="page-content">${state.coupon?`<section class="wallet-card"><div class="coupon-icon">10%</div><div style="flex:1"><h2>10% 點數回饋券</h2><p>下次兌換指定商品，享點數回饋</p><p style="margin-top:14px">${button('使用','coupon-use','btn orange')}</p></div></section>`:''}${state.redeemed?'<section class="wallet-card"><div class="crop-sogo" style="width:100px;height:120px;border-radius:18px;flex:none"></div><div><h2>已兌換的電子票券</h2><p>可於此查看與管理票券</p></div></section>':''}${!state.coupon&&!state.redeemed?'<div class="empty-message">目前沒有這次旅程新增的票券</div>':''}${button('回 GO驚喜','return-category','btn light full')}</div></article>`;}
const quick=['我的點數快過期了嗎？','推薦我可以兌換的商品','今天還有什麼任務？','幫我找生活優惠'];
function renderAI(){return `<article class="ai-page">${topbar(art('robot')+'<span>AI 點數管家</span>')}<div class="ai-subtitle">◆ 鑽點會員專屬</div><div class="ai-scroll" id="conversation" role="log" aria-label="與 AI 點數管家的對話" aria-live="polite"><div class="ai-message-row"><div class="bot-avatar">${art('robot')}</div><div class="bubble">嗨，吳*花！今天想怎麼使用你的點數？我可以幫你查點數、找優惠、推薦兌換，也可以提醒你還有哪些任務可以完成。</div></div><div class="quick-title">你可以這樣問我</div><div class="quick-grid">${quick.map((q,i)=>button(icon(['clock','gift','task','ticket'][i])+q,'ask','',`data-question="${escape(q)}"`)).join('')}</div>${state.chat.map(messageHTML).join('')}</div><form class="ai-input" id="ai-form"><input id="ai-text" aria-label="輸入你想問的問題" placeholder="輸入你想問的問題…" autocomplete="off" maxlength="300"><button type="submit" aria-label="送出訊息">${icon('send')}</button></form></article>`;}
function messageHTML(m){let html=`<div class="ai-message-row ${m.role==='user'?'user':''}">${m.role==='user'?'':`<div class="bot-avatar">${art('robot')}</div>`}<div class="bubble">${escape(m.text).replace(/\n/g,'<br>')}</div></div>`;if(m.cards==='recommend')html+=`<div class="recommendations"><article class="recommendation"><div class="rec-art">${art('coco')}</div><div><h3>CoCo 都可珍珠鮮奶</h3><p>260 點</p>${button('查看票券','coco-detail')}</div></article><article class="recommendation"><div class="rec-art">${art('life-ticket')}</div><div><h3>生活票券</h3><p>500 點・示範推薦</p>${button('立即查看','sample-ticket')}</div></article><article class="recommendation"><div class="rec-art" style="background:#fff4e1;display:grid;place-items:center;font-size:48px">Ⓟ</div><div><h3>${state.balance} 點內可兌商品</h3><p>依可用點數篩選</p>${button('看更多','more-tickets')}</div></article></div>`;if(m.cards==='task')html+=`<div class="recommendations"><article class="recommendation"><div class="rec-art" style="background:url('assets/tasks.png') 50% 20% / 200% auto"></div><div><h3>蘭蔻指定簽到任務</h3><p>${state.claimed?'今日彩蛋已領取':'彩蛋加碼 10 點'}</p>${button('查看任務','egg-task')}</div></article></div>`;if(m.cards==='offers')html+=`<div class="recommendations"><article class="recommendation"><div class="rec-art crop-offer"></div><div><h3>生活優惠</h3><p>為你整理合作商家活動</p>${button('查看優惠','offer')}</div></article></div>`;if(m.cards==='preference')html+='<div class="pref-chips"><span>多推薦美食</span><span>少推薦遊戲</span></div>';return html;}
function scrollChat(){schedule(()=>{const el=document.getElementById('conversation');if(el)el.scrollTop=el.scrollHeight;},30);}
function ask(q){if(!q.trim())return;const text=q.trim().slice(0,300);state.chat.push({role:'user',text});state.pending=(state.pending||0)+1;const conversation=document.getElementById('conversation');conversation.insertAdjacentHTML('beforeend',messageHTML(state.chat[state.chat.length-1]));document.getElementById('ai-text').value='';scrollChat();schedule(()=>{if(current.page!=='ai')return;const reply=replyTo(text);state.pending=Math.max(0,(state.pending||1)-1);state.chat.push(reply);document.getElementById('typing')?.remove();document.getElementById('conversation').insertAdjacentHTML('beforeend',messageHTML(reply));scrollChat();},650);}
function replyTo(text){if(/多推薦|少推薦|偏好|不要.*遊戲/.test(text)){state.preferences=true;return{role:'assistant',text:'好的，我記住了：多推薦美食、少推薦遊戲活動。我會調整各類型裡的推薦內容，你仍可自行切換消費購物、遊戲玩樂、生活娛樂。',cards:'preference'};}if(/過期|到期/.test(text))return{role:'assistant',text:`你目前有 ${state.balance} 點。這次示範資料中，有 200 點將於 2026/10/31 到期，可以優先挑選適合的票券使用。`,cards:'recommend'};if(/任務|簽到|還差|條件|怎麼.*完成/.test(text))return{role:'assistant',text:state.claimed?'你已完成本次指定任務，也收下額外 10 點。今天還可以看看其他優惠與票券。':'今天可以完成蘭蔻簽到任務：打開今日彩蛋，選擇指定任務，完成簽到並按「確定」，就能收下額外 10 點。',cards:'task'};if(/優惠|餐廳|週末|台北|生活好康/.test(text))return{role:'assistant',text:'我先為你整理 HAPPY GO 的生活優惠。你也可以告訴我想找的地點、消費類型或預算，讓推薦更符合你的需要。',cards:'offers'};if(/推薦|兌換|飲料|奶茶|美食|票券/.test(text))return{role:'assistant',text:`你目前有 ${state.balance} 點，依照可用點數與過往偏好，我整理了幾個適合你的選擇。`,cards:'recommend'};if(/幾點|多少|點數|明細|紀錄/.test(text))return{role:'assistant',text:`你目前可用的 HAPPY GO 點數為 ${state.balance} 點。${state.claimed?'其中包含剛剛收下的 10 點驚喜。':''}我可以幫你查到期時間，也能推薦可兌換的商品。`};return{role:'assistant',text:'我可以幫你查點數、推薦兌換、提醒任務與找生活優惠。你可以試著問「推薦我可以兌換的商品」，或告訴我「多推薦美食、少推薦遊戲」。'};}
function returnCategory(){history=[];navigate('category',{},false);}
function handle(action,el){switch(action){
case 'selection':navigate('selection');break;
case 'choose-shop':enterCategory('shop');break;case 'choose-play':enterCategory('play');break;case 'choose-life':enterCategory('life');break;
case 'banner-slide':setBanner(el.closest('[data-banner]'),Number(el.dataset.index));break;
case 'tab':state.category=el.dataset.type;navigate('category',{},false);break;
case 'back':back();break;case 'close':overlay.innerHTML='';resumeFab();break;
case 'eggs':showEggs();break;
case 'egg-task':state.fromEgg=true;navigate('task-list');break;
case 'task-detail':navigate('task-detail');break;
case 'sign':sign();break;
case 'signed-confirm':if(state.claimed){returnCategory();toast('今日彩蛋加碼已領取');}else surprise('points');break;
case 'signed-more':overlay.innerHTML='';toast('簽到活動已完成，按「確定」即可收下彩蛋');sign();break;
case 'claim-points':case 'claim-return':if(!state.claimed){state.claimed=true;state.balance+=10;}returnCategory();toast('已收下驚喜，HAPPY GO 點數 +10');break;
case 'egg-ticket':state.fromEgg=true;navigate('ticket-detail');break;
case 'ticket-detail':state.fromEgg=false;navigate('ticket-detail');break;
case 'coco-detail':state.fromEgg=false;navigate('coco-detail');break;
case 'quantity':state.qty=1;navigate('quantity',{product:'sogo'});break;
case 'quantity-coco':state.qty=1;navigate('quantity',{product:'coco'});break;
case 'minus':case 'plus':state.qty=Math.max(1,Math.min(3,state.qty+(action==='plus'?1:-1)));document.getElementById('qty').textContent=state.qty;document.getElementById('total').textContent='Ⓟ '+state.qty*(current.product==='coco'?260:200);break;
case 'redeem-confirm':redeemConfirm();break;case 'redeem':if(!el.disabled){el.disabled=true;redeem();}break;
case 'redemption-next':if(state.fromEgg&&!state.coupon)surprise('ticket');else navigate('wallet');break;
case 'claim-coupon':state.coupon=true;navigate('wallet');toast('10% 點數回饋券已加入我的票券');break;
case 'coupon-use':modal('<h2>10% 點數回饋券</h2><p>下次兌換指定商品，可享點數 10% 回饋。<br>兌換 100 點商品，可再獲得 10 點。</p>'+button('查看指定票券','ticket-detail','btn full'));break;
case 'egg-carrier':navigate('invoice');break;case 'invoice':navigate('invoice');break;
case 'link-carrier':state.linked=true;modal('<h2>專屬優惠已解鎖</h2><p>已完成載具重新綁定。<br>你的專屬優惠已準備好了！</p>'+button('收下驚喜','return-category','btn orange full'));break;
case 'ai':if(el.classList.contains('collapsed')){pauseFab();el.classList.remove('collapsed');resumeFab();}else navigate('ai');break;
case 'ask':ask(el.dataset.question);break;
case 'return-category':returnCategory();break;
case 'campaign-progress':modal('<h2>消費加碼活動進度</h2><p>消費滿7筆贈100點</p><div class="progress" role="progressbar" aria-label="消費筆數" aria-valuemin="0" aria-valuemax="7" aria-valuenow="'+state.consumptionCount+'"><span style="width:'+Math.min(state.consumptionCount/7*100,100)+'%"></span></div><p>目前 '+state.consumptionCount+'／7 筆，還差 '+Math.max(0,7-state.consumptionCount)+' 筆消費。</p>'+button('確定','close','btn full'));break;
case 'campaign-info':modal('<h2>【鑽點購物紅包】</h2><p>消費滿7筆贈100點。完成 7 筆消費，即可獲贈 100 點 HAPPY GO 點數。</p><p style="font-size:20px">活動素材截止日期：2026/10/31</p>'+button('查看進度','campaign-progress','btn full'));break;
case 'invoice-forest':navigate('invoice-forest');break;
case 'daily-task-info':modal('<h2>點數補給計畫</h2><p>完成指定任務贈30點。<br>請依活動說明完成指定任務。</p>'+button('查看任務','daily-task-go','btn full'));break;
case 'daily-task-go':navigate('service',{title:'點數補給計畫',description:'完成指定任務贈30點。任務條件與點數發放依當期活動說明。',visualAsset:'task-points-supply-wide'});break;
case 'ticket-event':modal('<h2>兌點加碼活動</h2><p>累積兌點滿 240 點，贈 10 點。</p>'+button('前往兌換','coco-detail','btn full'));break;
case 'offer':navigate('service',{title:'優惠活動',description:'查看 HAPPY GO 合作品牌的精選優惠。',asset:'offers',position:'60%'});break;
case 'shopping':navigate('service',{title:'購賺點',description:'生活每一筆都值得被回饋，透過購賺點前往合作商家。',asset:'shopping'});break;
case 'games':navigate('service',{title:'遊戲樂園',description:'探索遊戲與指定任務，完成任務賺 HAPPY GO 點數。'});break;
case 'health':navigate('service',{title:'GO HEALTH',description:'動腦遊戲、健康小學堂與健康任務，讓健康有人陪。'});break;
case 'utag':navigate('service',{title:'旅遊交通',description:'HAPPY GO 點數折抵、國道儲值與行車生活服務。'});break;
case 'settings':modal('<h2>設定</h2><p>可透過 AI 點數管家調整推薦內容的偏好。</p>'+button('管理我的偏好','ai','btn full'));break;
case 'fortune':navigate('fortune');break;
case 'tool-service':{const t=toolDefaults[state.category][Number(el.dataset.toolIndex)];navigate('service',{title:t.label,description:t.description,toolIcon:t.asset});break;}
case 'edit-tools':modal('<h2>自訂小工具</h2><p>'+labels[state.category]+'的預設入口：<br>'+toolDefaults[state.category].map(t=>t.label).join('、')+'。</p>'+button('完成','close','btn full'));break;
case 'sample-ticket':modal('<h2>生活票券</h2><p>這是 500 點生活票券的示範推薦卡。<br>正式商品會依當期票券內容提供。</p>'+button('查看其他票券','more-tickets','btn full'));break;
case 'more-tickets':state.category='life';returnCategory();break;
case 'gift-info':toast('本次展演請選擇「立即兌換」');break;
}}
window.addEventListener('message',e=>{const frame=screen.querySelector('.fortune-frame');if(frame&&e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.type==='fortune-return')back();});
document.addEventListener('pointerdown',noteFabActivity,{passive:true});
document.addEventListener('keydown',noteFabActivity);
document.addEventListener('wheel',noteFabActivity,{passive:true});
screen.addEventListener('scroll',noteFabActivity,{passive:true});
document.addEventListener('visibilitychange',()=>{pauseFab();resumeFab();});
reducedMotion.addEventListener('change',()=>{pauseFab();resumeFab();});
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)handle(el.dataset.action,el);});
document.addEventListener('submit',e=>{if(e.target.id==='ai-form'){e.preventDefault();if(e.isComposing)return;ask(document.getElementById('ai-text').value);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')back();if(e.key==='Tab'&&overlay.innerHTML){const items=[...overlay.querySelectorAll('button,input,[tabindex="0"]')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
document.getElementById('restart').addEventListener('click',()=>reset(true));
document.getElementById('fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('可使用瀏覽器的全螢幕模式'));});
function resize(){const mobile=window.innerWidth<=700;const availableHeight=window.innerHeight-(mobile?48:86);const s=Math.min((window.innerWidth-(mobile?0:40))/640,availableHeight/1334,mobile?1:.72);document.documentElement.style.setProperty('--scale',s);}
window.addEventListener('resize',resize);resize();reset();
})();


